### ISSUE TITLE
opengl examples

### ISSUE THREAD

**Issue by wasawi** [Cycling74/min-devkit#111]
Hello,
I´d like to know if there will be examples for the opengl part of jitter.
Thank you for any information.
J

**Comment by tap** [comment]
Hi Jordi,

There is nothing preventing it. To this point we have only been adding functionality as use for it has demanded (following the YAGNI principle).

Currently, our resources are somewhat limited due to focus on Max 8. But if there is anything we can do to help with either adding the functionality or creating an OpenGL object using a mixture of Min and classic Max SDK calls then let us know and we'll do our best!

**Comment by wasawi** [comment]
Thank you very much Tim,
I just found jit.mo examples and noticed i can start learning about opengl in Max from there.
Thanks,
J

**Comment by tap** [comment]
We are tracking OpenGL support in Cycling74/min-api#78
